# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NormalCFA <- function(inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior = 3.0, beta_prior = 2.0, sigma_prior = 10.0, sigma_cross_loading_prior = 0.0, wishart_degree_freedom_prior = 4, burnin = 1000L, samples = 1000L, seed = 0L) {
    invisible(.Call(`_tCFA_NormalCFA`, inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior, beta_prior, sigma_prior, sigma_cross_loading_prior, wishart_degree_freedom_prior, burnin, samples, seed))
}

StudentCFA <- function(inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior = 3.0, beta_prior = 2.0, sigma_prior = 10.0, sigma_cross_loading_prior = 0.0, wishart_degree_freedom_prior = 4, max_t_degree_freedom_prior = 300, burnin = 1000L, samples = 1000L, seed = 0L) {
    invisible(.Call(`_tCFA_StudentCFA`, inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior, beta_prior, sigma_prior, sigma_cross_loading_prior, wishart_degree_freedom_prior, max_t_degree_freedom_prior, burnin, samples, seed))
}

NormalCalculateMargLikl <- function(inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior = 3.0, beta_prior = 2.0, sigma_prior = 10.0, sigma_cross_loading_prior = 0.0, wishart_degree_freedom_prior = 4, samplesz = 1000L, replicationnumber = 10L) {
    .Call(`_tCFA_NormalCalculateMargLikl`, inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior, beta_prior, sigma_prior, sigma_cross_loading_prior, wishart_degree_freedom_prior, samplesz, replicationnumber)
}

StudentCalculateMargLikl <- function(inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior = 3.0, beta_prior = 2.0, sigma_prior = 10.0, sigma_cross_loading_prior = 0.0, wishart_degree_freedom_prior = 4, nu_max = 300, samplesz = 1000L, replicationnumber = 10L) {
    .Call(`_tCFA_StudentCalculateMargLikl`, inputFilePath, modelString, mcmcOutFilePath, mcmcLatentOutFilePath, alpha_prior, beta_prior, sigma_prior, sigma_cross_loading_prior, wishart_degree_freedom_prior, nu_max, samplesz, replicationnumber)
}

